"""empty message

Revision ID: 1077304e4e17
Revises: 3e6161dac574
Create Date: 2025-05-09 20:28:39.359174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1077304e4e17'
down_revision: Union[str, None] = '3e6161dac574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_attendee_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('organiser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_organiser_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organiser', schema=None) as batch_op:
        batch_op.drop_constraint('fk_organiser_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('attendee', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendee_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
