"""empty message

Revision ID: 8c44dae03e97
Revises: b640cc9c359a
Create Date: 2025-06-03 14:05:50.446627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8c44dae03e97'
down_revision: Union[str, None] = 'b640cc9c359a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perk_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('registration_type')
        batch_op.drop_column('registration_type_perks')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_type_perks', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('registration_type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('approved_date')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('perk_id')

    # ### end Alembic commands ###
