"""empty message

Revision ID: b0d66bb499c1
Revises: 2157298a8084
Create Date: 2025-05-20 12:03:57.211740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b0d66bb499c1'
down_revision: Union[str, None] = '2157298a8084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisereventlink',
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['organiser_id'], ['organiser.id'], ),
    sa.PrimaryKeyConstraint('organiser_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisereventlink')
    # ### end Alembic commands ###
