"""empty message

Revision ID: 02e7580b4652
Revises: 1077304e4e17
Create Date: 2025-05-12 20:21:07.515380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '02e7580b4652'
down_revision: Union[str, None] = '1077304e4e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_perks_id', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_registration_id', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('perks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
